apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 009160038179.dkr.ecr.us-east-1.amazonaws.com/registry:frontend-0d729bed3e8f3a490c304a75bcc6ef8a2a4738d5
        ports:
        - containerPort: 80
  