apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 009160038179.dkr.ecr.us-east-1.amazonaws.com/registry:frontend-ee7f2173794e1e05411b01451216a43d337dba8f
        ports:
        - containerPort: 80
  