apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 009160038179.dkr.ecr.us-east-1.amazonaws.com/registry:frontend-dcddd49a2208f6a816cae69296d84cc3c8bc6e20
        ports:
        - containerPort: 80
  