name: CI_FRONTEND

on:
  push:
    branches:
      - argocd
    paths:
      - 'frontend/**'

env:
  IMAGE_TAG: frontend-${{ github.sha }}    

permissions:
  contents: write
jobs:

 build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login no Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build da imagem Docker
        run: |
          docker build -t fortune-cookie-frontend ./frontend

      - name: Tag da imagem
        run: |
          docker tag fortune-cookie-frontend:latest 009160038179.dkr.ecr.us-east-1.amazonaws.com/registry:${IMAGE_TAG}

      - name: Push para o ECR
        run: |
          docker push 009160038179.dkr.ecr.us-east-1.amazonaws.com/registry:${IMAGE_TAG}
      
      - name: alterando imagem nos manifestos kubernetes
        run: |
          sed -i "s|image:.*|image: 009160038179.dkr.ecr.us-east-1.amazonaws.com/registry:${IMAGE_TAG}|g" k8s-manifests/frontend-deployment.yaml
      
      - name: Commit e push da alteração
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git add k8s-manifests/frontend-deployment.yaml

          git commit -m "Atualizando imagem frontend ${IMAGE_TAG} [skip ci]" || echo "Sem alterações"

          git push origin argocd